import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DeleteModal from "@/components/delete-modal";
import { Providers } from "@/providers/jotai-provider";
import NewCharacterModalModal from "@/components/new-character-modal";
import NewCharacterCancelModal from "@/components/new-character-cancel-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <DeleteModal />
          <NewCharacterModalModal />
          <NewCharacterCancelModal />
        </Providers>
      </body>
    </html>
  );
}
